### ISSUE TITLE
TASK os_neutron: Updating linuxbridge_agent.ini FAILS

### ISSUE THREAD

**Issue by scalzolari** [sandvine-eng/svauto#1]
TASK [os_neutron : Updating linuxbridge_agent.ini] *****************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleError: ERROR! template error while templating string: Encountered unknown tag 'os_neutron_cmpt'."}

PLAY RECAP *********************************************************************
localhost                  : ok=121  changed=101  unreachable=0    failed=1

**Comment by tmartinx** [comment]
Fixed.
