### ISSUE TITLE
os-deploy.sh fails to install a proper environment

### ISSUE THREAD

**Issue by scalzolari** [sandvine-eng/svauto#2]
From what I can see from the syslog entries the first problem with the installation if keystone not coming up online correctly.

`Jun 27 23:39:38 mitaka-1 keystone[6159]: 2016-06-27 23:39:38.496 6159 INFO keystone.common.environment.eventlet_server [req-6fda389e-2096-4f78-a94f-983148547c91 - - - - -] Starting /usr/bin/keystone-all on 0.0.0.0:35357
Jun 27 23:39:38 mitaka-1 keystone[6159]: 2016-06-27 23:39:38.496 6159 INFO oslo_service.service [req-6fda389e-2096-4f78-a94f-983148547c91 - - - - -] Starting 4 workers
Jun 27 23:39:38 mitaka-1 keystone[6159]: 2016-06-27 23:39:38.501 6159 INFO keystone.common.environment.eventlet_server [req-6fda389e-2096-4f78-a94f-983148547c91 - - - - -] Starting /usr/bin/keystone-all on 0.0.0.0:5000
Jun 27 23:39:38 mitaka-1 keystone[6159]: 2016-06-27 23:39:38.501 6218 INFO eventlet.wsgi.server [req-6fda389e-2096-4f78-a94f-983148547c91 - - - - -] (6218) wsgi starting up on http://0.0.0.0:35357
Jun 27 23:39:38 mitaka-1 keystone[6159]: 2016-06-27 23:39:38.502 6159 INFO oslo_service.service [req-6fda389e-2096-4f78-a94f-983148547c91 - - - - -] Starting 4 workers
Jun 27 23:39:38 mitaka-1 keystone[6159]: 2016-06-27 23:39:38.506 6219 INFO eventlet.wsgi.server [req-6fda389e-2096-4f78-a94f-983148547c91 - - - - -] (6219) wsgi starting up on http://0.0.0.0:35357
Jun 27 23:39:38 mitaka-1 keystone[6159]: 2016-06-27 23:39:38.509 6222 INFO eventlet.wsgi.server [req-6fda389e-2096-4f78-a94f-983148547c91 - - - - -] (6222) wsgi starting up on http://0.0.0.0:5000
Jun 27 23:39:38 mitaka-1 keystone[6159]: 2016-06-27 23:39:38.513 6220 INFO eventlet.wsgi.server [req-6fda389e-2096-4f78-a94f-983148547c91 - - - - -] (6220) wsgi starting up on http://0.0.0.0:35357
Jun 27 23:39:38 mitaka-1 keystone[6159]: 2016-06-27 23:39:38.517 6221 INFO eventlet.wsgi.server [req-6fda389e-2096-4f78-a94f-983148547c91 - - - - -] (6221) wsgi starting up on http://0.0.0.0:35357
Jun 27 23:39:38 mitaka-1 keystone[6159]: 2016-06-27 23:39:38.520 6223 INFO eventlet.wsgi.server [req-6fda389e-2096-4f78-a94f-983148547c91 - - - - -] (6223) wsgi starting up on http://0.0.0.0:5000
Jun 27 23:39:38 mitaka-1 keystone[6159]: 2016-06-27 23:39:38.524 6224 INFO eventlet.wsgi.server [req-6fda389e-2096-4f78-a94f-983148547c91 - - - - -] (6224) wsgi starting up on http://0.0.0.0:5000
Jun 27 23:39:38 mitaka-1 keystone[6159]: 2016-06-27 23:39:38.527 6225 INFO eventlet.wsgi.server [req-6fda389e-2096-4f78-a94f-983148547c91 - - - - -] (6225) wsgi starting up on http://0.0.0.0:5000
Jun 27 23:39:39 mitaka-1 ansible-service: Invoked with name=keystone pattern=None enabled=None state=stopped sleep=None arguments= runlevel=default
Jun 27 23:39:39 mitaka-1 systemd[1]: Stopping OpenStack Identity service...`

Issue also with nova:

` 27 23:46:31 mitaka-1 systemd[1]: Started OpenStack Compute Console.
Jun 27 23:46:31 mitaka-1 nova-api[11805]: 2016-06-27 23:46:31.383 11805 WARNING oslo_reports.guru_meditation_report [-] Guru mediation now registers SIGUSR1 and SIGUSR2 by default for backward compatibility. SIGUSR1 will no longer be registered in a future release, so please use SIGUSR2 to generate reports.
Jun 27 23:46:31 mitaka-1 nova-api[11805]: 2016-06-27 23:46:31.385 11805 ERROR nova.wsgi [-] Couldn't lookup app: ec2`

Finally one of the ansible neutron task fails when trying to setup the external network:

`TASK [os_ext_net : Creating Neutron External Network] **************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "neutron net-create ext-net --router:external --provider:physical_network external --provider:network_type flat", "delta": "0:00:01.006797", "end": "2016-06-27 23:55:01.827281", "failed": true, "rc": 1, "start": "2016-06-27 23:55:00.820484", "stderr": "Unable to establish connection to http://mitaka-1.yourdomain.com:9696/v2.0/networks.json", "stdout": "", "stdout_lines": [], "warnings": []}

PLAY RECAP *********************************************************************
localhost                  : ok=130  changed=109  unreachable=0    failed=1`

**Comment by tmartinx** [comment]
Fixed!
